default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-comprehensions = "^3.10.1"
            flake8-implicit-str-concat = "^0.3.0"
            flake8-literal = "^1.3.0"
            flake8-multiline-containers = "^0.0.19"
            flake8-return = "^1.2.0"
            flake8-broken-line = "^0.6.0"
            flake8-builtins = "^2.0.1"
            flake8-functions-names = "^0.4.0"
            pep8-naming = "^0.13.2"
            flake8-expression-complexity = "^0.0.11"
            flake8-functions = "^0.0.7"
            flake8-length = "^0.3.1"
            flake8-comments = "^0.1.2"
            flake8-eradicate = "^1.4.0"
            flake8-docstrings = "^1.6.0"
            flake8-docstring-checker = "^1.1"
            flake8-annotations = "^2.9.1"
            flake8-fastapi = "^0.7.0"
            pandas-vet = "^0.2.3"
            pre-commit = "^2.9.3"
        ]
